version: "3"

services:
  mongodb:
    container_name: ${DB_CONTAINER_NAME}
    image: "mongo:4.2.16-bionic"
    environment:
        - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
        - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
        - MONGO_INITDB_DATABASE=${DB_NAME}
    ports:
      - "27017:27017"